global using AirRouteManagementSystem.UnitOfWork.Interface;
global using AirRouteManagementSystem.UnitOfWork;
global using AirRouteManagementSystem.DateAccess.Context;
global using AirRouteManagementSystem.DBSeder.Interface;
global using AirRouteManagementSystem.DBSeder;